on: push

name: Jira ANY > In Progress

jobs:
  build:
    runs-on: ubuntu-latest
    name: Find and Transition Issue

    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits

    - name: Transition Issue
      id: transition
      uses: atlassian/gajira-transition@master
      if: ${{ steps.find.outputs.issue }}
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "In Progress"
